[project]
name = "doc-ingestion-service"
version = "0.1.0"
description = "FastAPI microservice for dynamic document ingestion and text extraction"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi[standard]>=0.141.1",
    "fit>=0.5.1",
    "opentelemetry-api>=1.44.0",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-exporter-otlp-proto-grpc>=1.44.0",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "opentelemetry-instrumentation-httpx>=0.65b0",
    "opentelemetry-instrumentation-qdrant>=0.62.3",
    "opentelemetry-sdk>=1.44.0",
    "pdfplumber>=0.11.10",
    "prometheus-fastapi-instrumentator>=8.1.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pymupdf>=1.28.0",
    "pypdf>=6.14.2",
    "python-multipart>=0.0.32",
    "qdrant-client>=1.19.0",
    "requests>=2.34.2",
    "streamlit>=1.62.0",
    "streamlit-lottie>=0.0.5",
    "tiktoken>=0.13.0",
    "uvicorn[standard]>=0.52.1",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "mypy>=2.3.0",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
]

[tool.pylint.main]
# Tells Pylint to look at your root directory or specific source folders
init-hook = "import sys; import os; sys.path.append(os.path.abspath('.'))"
# Specify the files or directories to lint
ignore = ["tests", "scripts", "logs", "grafana", "qdrant_storage"]

[tool.pylint.messages_control]
# Disable specific lint errors if needed
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "R0903", # Too few public methods
    "E0401", # Unable to import,
    "W0718", # Catching too general exception Exception
    "R0914", # Too many local variables
    "R0902", # Too many instance attributes
    "R0801", # Similar lines in 2 files
]

[tool.pylint.format]
max-line-length = 90
